
[1]
NAME=ChannelOne
CALLSIGN=One
TUNE="${TUNER} --prologue"
# XONCOUNT will typically be 2 when mythbackend is actually starting to record.
XON="${TUNER} --epilogue --xon-cnt ${XONCOUNT}"
TIMEOUT=90000

[2]
NAME=ChannelTwo
CALLSIGN=Two
TUNE="${TUNER} [{--seriesid \"${SERIESID}\"}] [{--programid \"${PROGRAMID}\"}] --prologue"
# ONSTART triggers when the first bytes are received from the external program.
ONSTART="${TUNER} [{--seriesid \"${SERIESID}\"}] [{--programid \"${PROGRAMID}\"}] --epilogue"
TIMEOUT=90000
