
[1]
NAME=ChannelOne
CALLSIGN=One
TUNE="${TUNER} --prologue"
ONSTART="${TUNER} --epilogue"
TIMEOUT=90000

[2]
NAME=ChannelTwo
CALLSIGN=Two
TUNE="${TUNER} [{--seriesid \"${SERIESID}\"}] [{--programid \"${PROGRAMID}\"}] --prologue"
ONSTART="${TUNER} [{--seriesid \"${SERIESID}\"}] [{--programid \"${PROGRAMID}\"}] --epilogue"
TIMEOUT=90000
