[RECORDER]
# The recorder command to execute.  ${URL} is optional, and
# will be replaced with the channel's "URL" as defined in the
# [TUNER/channels] (channel conf) configuration file
command="/usr/local/bin/magewell2ts -b ${BOARD} -i ${INPUT} -m -c ${CODEC} ${LOG}"
desc="${DEVICE}-${BOARD}-${INPUT}-${SOURCE}"

[TUNER]
# An optional CONF file which provides channel details.  If it does not
# exist, then channel changes are not supported.
channels=/home/mythtv/etc/OnDemand-channels.conf

# If [TUNER/command] is provided, it will be executed to "tune" the
# channel. A ${URL} parameter will be substituted with the "URL" as
# defined in the [TUNER/channels] configuration file
command=${TUNER} --debug --sourceid "${SOURCEID}" --callsign "${CALLSIGN}" --recordid "${RECORDID}"

# Timeout for changing channels in msecs
timeout=90000


[SCANNER]
# When MythTV scans for channels, The contents of the [TUNER/channels]
# config file are used to populate MythTV's channel information.
# If a command is provided here, it will be executed first, so it can
# populate the [TUNER/channels] config file
#command=/home/mythtv/mythtvguide/scan.sh "${CHANCONF%}"

# Timeout for scan command in msecs
#timeout=60000
