[VARIABLES]
BOARD=2
INPUT=1
SOURCE=4
DEVICE=roku9
LINK=${SERIESID}${PROGRAMID}
TUNER=/usr/local/bin/roku-control --device ${DEVICE}
CODEC=hevc_qsv --device renderD128 --p010 -q 21 --extra-hw-frames 96 --gpu-buffers 48 --video-buffers 48
LOG=-v 3 --logfile "/home/mythtv/log/mag-${BOARD}-${INPUT}-${SOURCE}.log"

[RECORDER]
# The recorder command to execute.  %URL% is optional, and
# will be replaced with the channel's "URL" as defined in the
# [TUNER/channels] (channel conf) configuration file
command="/usr/local/bin/magewell2ts -b ${BOARD} -i ${INPUT} -m -c ${CODEC} ${LOG}"
desc="${DEVICE}-${BOARD}-${INPUT}-${SOURCE}"

[TUNER]
# An optional CONF file which provides channel details.  If it does not
# exist, then channel changes are not supported.
channels=/home/mythtv/etc/Channels.conf
command=${TUNER} --debug --sourceid "${SOURCEID}" --callsign "${CALLSIGN}" --recordid "${RECORDID}"
timeout=30000
