[VARIABLES]
BOARD=2
INPUT=1
SOURCE=4
DEVICE=roku9
TUNER=/usr/local/bin/roku-control --device ${DEVICE}
CODEC=hevc_qsv --device renderD128 --p010 -q 16 --extra-hw-frames 64
LOG=-v 3 --logfile "/home/mythtv/log/mag-${BOARD}-${INPUT}-${SOURCE}.log"

# The TuneChannel command passes along extra variables which can be used:
# atsc_major, atsc_minor, callsign, chanid, channum,
# description, duration, freqid, inputid, mplexid, name, programid,
# recordid, seriesid, sourceid, subtitle, title

[INCLUDE]
magewell-${SOURCE}.conf
